# Generated by Django 4.2.1 on 2023-05-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img_url',
            field=models.URLField(default='N/A', max_length=600),
        ),
    ]
