# Generated by Django 4.2.1 on 2023-05-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0002_alter_movie_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImdbRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_rating', models.FloatField()),
                ('critic_rating', models.FloatField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userview.movie')),
            ],
        ),
    ]
